language: cpp
compiler:
  - clang
notifications:
  email: false
before_install:
  - sudo add-apt-repository ppa:staticfloat/julia-deps -y
  - sudo add-apt-repository ppa:staticfloat/juliareleases -y
  - sudo apt-get update -qq -y
  - sudo apt-get install libpcre3-dev julia -y
script:
  - julia -e 'versioninfo(); Pkg.init(); run(`ln -s $(pwd()) $(Pkg.dir("FinMarkets"))`); Pkg.pin("FinMarkets"); Pkg.resolve()'
  - julia -e 'using FinMarkets; @assert isdefined(:FinMarkets); @assert typeof(FinMarkets) === Module'
  - julia -e 'Pkg.test("FinMarkets", coverage=true)'
after_success:
- julia -e 'cd(Pkg.dir("FinMarkets")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
